encoding : utf-8
title: ROCEYS
blog_title: ROCEYS's Blog
travel: 基于移动互联网LBS智能灵活便捷的自由行解决方案 - ROCEYS东边山云网
description: 東邊山雲網
show_downloads: false
google_analytics: UA-105700856-1 #2019-01-08 13:59:02
theme: jekyll-theme-hacker
markdown: kramdown
domain: https://roceys.cn
#domain: http://127.0.0.1:4000
timezone: Asia/Shanghai
paginate: 5
baseurl: ""
cdn: https://cdn.jsdelivr.net/gh/roceys/static@2.7
#baseurl: /blog
google_gajs: https://cdn.jsdelivr.net/npm/google-analytics-js@0.1.2/gajs.min.js

#pic
gavatar:
favicon: assets/images/favicon1.ico
logo:

# Markdown 处理器
kramdown:
  input: GFM

plugins: [jekyll-paginate]