encoding : utf-8
title: ROCEYS
blog_title: ROCEYS's Blog
travel: 基于移动互联网LBS智能灵活便捷的自由行解决方案 - ROCEYS东边山云网
description: 東邊山雲網
show_downloads: false
google_analytics: UA-105700856-1 #2019-01-08 13:59:02
theme: jekyll-theme-hacker
markdown: kramdown
domain: https://roceys.cn
#domain: http://127.0.0.1:4000
timezone: Asia/Shanghai
paginate: 5
baseurl: ""
google_gajs: https://cdn.jsdelivr.net/npm/google-analytics-js@0.1.2/gajs.min.js
staticcdn: https://cdn.jsdelivr.net/gh/roceys/static@2.7
cdn: https://git.imweb.io/roceys/static/raw/00c2e3701f90e4e3a41b10e0a545155b59601449
#cdn: https://gitee.com/ROCEYS-CN/static/raw/master

#pic
gavatar:
favicon: assets/images/favicon1.ico
logo:

# Markdown 处理器
kramdown:
  input: GFM

plugins: [jekyll-paginate]

gitalk:
  enable: true
  clientID: 5bb60bc3e2a81875f1d6
  clientSecret: 4eeafbdb7d687b144207dbe41243b845ba9e9a54
  repo: gitalk
  owner: ROCEYS
  admin: ROCEYS
  distractionFreeMode: true